# Auto-label configuration
# Label PRs based on changed files

documentation:
  - '**/*.md'
  - 'docs/**/*'

dependencies:
  - 'package.json'
  - 'package-lock.json'
  - 'requirements.txt'
  - 'Pipfile'
  - 'Pipfile.lock'
  - 'go.mod'
  - 'go.sum'

ci-cd:
  - '.github/workflows/**/*'
  - '.github/actions/**/*'

security:
  - 'SECURITY.md'
  - '.github/workflows/codeql.yml'

configuration:
  - '**/*.config.js'
  - '**/*.config.json'
  - '**/*.yml'
  - '**/*.yaml'
  - '.github/**/*'

testing:
  - '**/*.test.js'
  - '**/*.spec.js'
  - '**/*.test.ts'
  - '**/*.spec.ts'
  - 'test/**/*'
  - 'tests/**/*'
  - '__tests__/**/*'
